# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a958b99a67b0a1f4ac0a3369871e6bb0ddc1319b573e37c175247f971400944a876cd2435046a6a577fdcc3be8db863def914782ac56a81539395842c4da9c73

test:
  secret_key_base: ac2d4fb652d0ecf7db9f3f6f6b801d2285cfc26d2f8eca40e6991df1607281eed7e42b6904e01bfd15043a2d04b4633c85639c9d8d546e73b51aa4cf4d80ab9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
